--- #YAML:1.0
name:               Jit
version:            0.04_03
abstract:           Jit the perl5 runloop in proper execution order and near calls
author:
    - Reini Urban <perl-compiler@googlegroups.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    sigtrap:  1
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/rurban/Jit/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
